# deploy.yml
name: Deploy to Tencent Cloud
on:
  push:
    branches:
      - master
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout master
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: 'master'
      # Use Node:12
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      # Yarn install
      - name: Yarn install and Build
        run: |
          yarn install
          yarn build
      # Deploy to Tencent Cloud
      - name: Deploy to Tencent Cloud
        uses: easingthemes/ssh-deploy@v2.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACTION_MACHINE_KEY }}
          ARGS: "-avz --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"